---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:

- name: verify
  image: php-dev:7.1
  commands:
    - composer install
    - vendor/bin/phpunit
    - vendor/bin/phpunit tests

